apiVersion: v1
kind: Service
metadata:
  {{- include "rick-and-morty.name" . | nindent 2 }}
  {{- include "rick-and-morty.namespace" . | nindent 2 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rick-and-morty.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
